go_import_path: github.com/vasary/merger

language: go

go:
  - "1.10"

dist: trusty

branches:
  only:
    - master

env:
  - DEP_VERSION="0.4.1"

script:
  go test -v ./...

notifications:
  email: false