go_import_path: merger
sudo: required
language: go

go:
  - "1.10"

dist: trusty

env:
  - DATABASE_HOST=localhost
  - DATABASE_NAME=userdata
  - DATABASE_PASSWORD=postgres
  - DATABASE_PORT=5432
  - DATABASE_USER=postgres
  - LOG_PATH=/var/app/logs.log

branches:
  only:
    - master

before_install:
  - sudo mkdir -p /var/app
  - sudo touch /var/app/logs.log
  - curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - dep ensure

script:
  go test -v -coverprofile c.out ./...

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false