language: go
go:
  - "1.10"

before_install:
  - echo "Test message"
  - echo $TRAVIS
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_PULL_REQUEST_SHA
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_SECURE_ENV_VARS
  - go -v
  - pwd

install:
  - pwd
  - go -v
  - go get -v ./...

script:
  - go test -v ./...