language: go
go:
  - "1.10"

os:
  - linux

before_install:
  - echo $TRAVIS
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_PULL_REQUEST_SHA
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_SECURE_ENV_VARS

install:
  - "go get -v github.com/golang/dep"
  - "dep ensure"

script:
  - "go test -v ./..."