language: go
go:
  - 1.10
  - master

install: true

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get -u github.com/golang/dep/cmd/dep

script:
  - go test -v ./...