language: go

go:
  - "1.10"

go_import_path: github.com/vasary/merger

branches:
  only:
    - master

env:
  - DEP_VERSION="0.4.1"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

script:
  go test -v ./...