go_import_path: merger

language: go

go:
  - "1.10"

dist: trusty

branches:
  only:
    - master

env:
  - DEP_VERSION="0.4.1"
  - GOROOT=/usr/local/go
  - GOPATH=$HOME/go
  - PATH=$PATH:$GOROOT/bin
  
script:
  go test -v ./...

notifications:
  email: false