[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.1"

[[constraint]]
  branch = "master"
  name = "github.com/bradfitz/slice"

[[constraint]]
  name = "github.com/Selvatico/go-mocket"
  version = "1.0.4"
